# This is a basic workflow to help you get started with Actions

name: CI


on: push

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
  
      - name: pytest
        run: PYTHONPATH=./library py.test ./tests -x -vv
