name: pytest


on: push


jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set-up
        run: python3.8 -m pip install -r ./etc/requirements.txt

      - name: pytest
        run: ./test.sh pytest
