-  py-execExternalFunction:
    from: std.base.projectConfig
    import: loadHandlerPyExternalKey


-  py-externalKey:
    from: std.base.projectConfig
    import: getRules
    name: rules


-  py-externalKey:
    from: std.base.projectConfig
    import: getScope
    name: scope


-  py-externalKey:
    from: std.base.projectConfig
    import: getInput
    name: input


-  py-externalKey:
    from: std.base.projectConfig
    import: getParser
    name: parser


-  py-externalKey:
    from: std.base.projectConfig
    import: getExecutor
    name: executor


-  py-externalKey:
    from: std.base.projectConfig
    import: getBuild
    name: build
