-  py-execExternalFunction:
    from: std.base.projectConfig
    import: loadHandlerPyExternalKey


-  py-externalKey:
    from: std.base.projectConfig
    import: getRules
    name: rules


-  py-externalKey:
    from: std.base.projectConfig
    import: Importer
    name: import


-  py-externalKey:
    from: std.base.projectConfig
    import: getInitialScope
    name: initialScope


-  py-externalKey:
    from: std.base.projectConfig
    import: getParseInput
    name: parseInput


-  py-externalKey:
    from: std.base.projectConfig
    import: getBuild
    name: build


-  py-externalKey:
    from: std.base.projectConfig
    import: getBuildScope
    name: buildScope


-  py-externalKey:
    from: std.base.projectConfig
    import: getBuildExecutor
    name: buildExecutor


-  py-externalKey:
    from: std.base.projectConfig
    import: getLibraryDirectory
    name: libraryDirectory
